name: qm_gnn

channels:
  - conda-forge
  - rdkit

dependencies:
  - pip>=20.0.0
  - python=3.6
  - tqdm
  - pandas=1.1.0
  - numpy=1.19
  - rdkit=2020.03.3.0
  - scipy>=1.4.1
  - scikit-learn>=0.22.2.post1
  - pip:
      - qmdesc
      - tensorflow==2.4
